In [2]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving master_banking.csv to master_banking.csv

In [3]:
import pandas as pd

df = pd.read_csv("master_banking.csv")
df.head()

,Client ID,Name,Age,Nationality,Occupation,Estimated Income,Bank Loans,Bank Deposits,Credit Card Balance,Business Lending,Banking Relationship,Gender,Investment Advisor
0,IND81288,Raymond Mills,24,American,Safety Technician IV,75384.77,776242.92,1485828.64,484.54,1134475.30,Retail,Male,Victor Dean
1,IND65833,Julia Spencer,23,African,Software Consultant,289834.31,1270615.43,641482.79,2256.88,2000526.10,Institutional,Male,Jeremy Porter
2,IND47499,Stephen Murray,27,European,Help Desk Operator,169935.23,1052715.84,1033401.59,4568.74,548137.58,Private Bank,Female,Ernest Knight
3,IND72498,Virginia Garza,40,American,Geologist II,356808.11,121195.06,1048157.49,4205.00,1148402.29,Commercial,Male,Eric Shaw
4,IND60181,Melissa Sanders,46,American,Assistant Professor,130711.68,1048301.95,487782.53,3779.49,1674412.12,Retail,Female,Kevin Kim

In [4]:
import os
os.listdir()

['.config', 'master_banking.csv', 'sample_data']

In [5]:
df['Total_Loan'] = (
    df['Bank Loans'] +
    df['Credit Card Balance'] +
    df['Business Lending']
)

In [6]:
df['Loan_to_Income'] = df['Total_Loan'] / df['Estimated Income']

In [7]:
def risk_category(x):
    if x > 0.6:
        return "High Risk"
    elif x > 0.3:
        return "Medium Risk"
    else:
        return "Low Risk"

df['Risk Category'] = df['Loan_to_Income'].apply(risk_category)

In [9]:
df.columns

Index(['Client ID', 'Name', 'Age', 'Nationality', 'Occupation',
       'Estimated Income', 'Bank Loans', 'Bank Deposits',
       'Credit Card Balance', 'Business Lending', 'Banking Relationship',
       'Gender', 'Investment Advisor', 'Total_Loan', 'Loan_to_Income',
       'Risk Category'],
      dtype='object')

In [10]:
from google.colab import files
uploaded = files.upload()

Saving master_banking_updated.c.csv to master_banking_updated.c.csv

In [12]:
import pandas as pd

df = pd.read_csv("master_banking_updated.c.csv")
df.head()

,Client ID,Name,Age,Nationality,Occupation,Joined Bank,Estimated Income,Bank Loans,Bank Deposits,Credit Card Balance,Business Lending,Banking Relationship,Gender,Investment Advisor
0,IND81288,Raymond Mills,24,American,Safety Technician IV,06-05-2019,75384.77,776242.92,1485828.64,484.54,1134475.30,Retail,Male,Victor Dean
1,IND65833,Julia Spencer,23,African,Software Consultant,10-12-2001,289834.31,1270615.43,641482.79,2256.88,2000526.10,Institutional,Male,Jeremy Porter
2,IND47499,Stephen Murray,27,European,Help Desk Operator,25-01-2010,169935.23,1052715.84,1033401.59,4568.74,548137.58,Private Bank,Female,Ernest Knight
3,IND72498,Virginia Garza,40,American,Geologist II,28-03-2019,356808.11,121195.06,1048157.49,4205.00,1148402.29,Commercial,Male,Eric Shaw
4,IND60181,Melissa Sanders,46,American,Assistant Professor,20-07-2012,130711.68,1048301.95,487782.53,3779.49,1674412.12,Retail,Female,Kevin Kim

In [13]:
df.columns = df.columns.str.strip()

In [14]:
df['Total_Loan'] = (
    df['Bank Loans'] +
    df['Credit Card Balance'] +
    df['Business Lending']
)

In [15]:
df['Loan_to_Income'] = df['Total_Loan'] / df['Estimated Income']

In [16]:
def risk_category(x):
    if x > 0.6:
        return "High Risk"
    elif x > 0.3:
        return "Medium Risk"
    else:
        return "Low Risk"

df['Risk Category'] = df['Loan_to_Income'].apply(risk_category)

In [17]:
df['Joined Bank'] = pd.to_datetime(df['Joined Bank'], errors='coerce')

df['Engagement Days'] = (
    pd.Timestamp.today() - df['Joined Bank']
).dt.days

In [18]:
def engagement_bucket(days):
    if days < 1825:
        return "<5 Years"
    elif days < 3650:
        return "<10 Years"
    else:
        return ">10 Years"

df['Engagement Bucket'] = df['Engagement Days'].apply(engagement_bucket)

In [19]:
def income_band(x):
    if x < 100000:
        return "Low"
    elif x < 300000:
        return "Mid"
    else:
        return "High"

df['Income Band'] = df['Estimated Income'].apply(income_band)

In [20]:
df[['Total_Loan', 'Loan_to_Income', 'Risk Category', 'Engagement Days']].head()

   Total_Loan  Loan_to_Income Risk Category  Engagement Days
0  1911202.76       25.352638     High Risk           2515.0
1  3273398.41       11.294034     High Risk           8960.0
2  1605422.16        9.447259     High Risk              NaN
3  1273802.35        3.569993     High Risk              NaN
4  2726493.56       20.858836     High Risk              NaN

In [21]:
df.to_csv("final_banking_dataset.csv", index=False)

from google.colab import files
files.download("final_banking_dataset.csv")